
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />

			<table border="1">
				<thead class="well">
				<tr>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th>วัน</th>
					<th>บาท</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th>วัน</th>
					<th>ชม.</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
				<tr>
					<th>ลำดับ</th>
					<th>รหัส<br>สาขา</th>
					<th>ประจำงวดเดือน</th>
					<th>ประจำงวดปี</th>
					<th>ประจำงวด</th>
					<th>วันที่จ่าย</th>
					<th>วันที่แสดงผล</th>
					<th>Employee<br>unique code</th>
					<th>Employee<br>code</th>
					<th>แผนก</th>
					<th>ประเภท</th>
					<th>ค่าจ้าง<br>(Base Salary)</th>
					<th>#startsalary</th>
					<th>ขาดงาน</th>
					<th>ขาดงาน</th>
					<th>กิจไม่ได้ค่าจ้าง</th>
					<th>กิจไม่ได้ค่าจ้าง</th>
					<th>กิจได้รับค่าจ้าง</th>
					<th>กิจได้รับค่าจ้าง</th>
					<th>พักร้อน</th>
					<th>พักร้อน</th>
					<th>ป่วย</th>
					<th>ป่วย</th>
					<th>อุบัติเหตุใน<br>งาน100</th>
					<th>อุบัติเหตุใน<br>งาน100</th>
					<th>อุบัติเหตุใน<br>งาน40</th>
					<th>อุบัติเหตุใน<br>งาน40</th>
					<th>ลาคลอด</th>
					<th>ลาคลอด</th>
					<th>วันหยุดประเพณี</th>
					<th>วันหยุดประเพณี</th>
					<th>วันลาอื่นๆ</th>
					<th>วันลาอื่นๆ</th>
					<th>{rfFormatCodeTextWorks1p}</th>
					<th>{rfFormatCodeTextWorks1p}</th>
					<th>{rfFormatCodeTextWorks2p}</th>
					<th>{rfFormatCodeTextWorks2p}</th>
					<th>{rfFormatCodeTextWorks3p}</th>
					<th>{rfFormatCodeTextWorks3p}</th>
					<th>shut down</th>
					<th>shut down</th>
					<th>วันทำงาน</th>
					<th>วันทำงาน</th>
					<th>#endsalary</th>
					<th>#startincome</th>
					<th>ค่าบอกกล่าว</th>
					<th>เงินค่าชดเชย</th>
					<th>คืนเงินประกัน</th>
					<th>ค่ากะ</th>
					<th>ค่าอาหาร</th>
					<th>ค่ารถ</th>
					<th>เบี้ยขยัน</th>
					<th>โบนัส</th>
					<th>ค่าครองชีพ</th>
					<th>ค่าโทร</th>
					<th>ค่าทักษะ</th>
					<th>ค่าตำแหน่ง</th>
					<th>ค่าน้ำมัน</th>
					<th>Incentive</th>
					<th>ค่าวิชาชีพ</th>
					<th>ค่าใบอนุญาติ</th>
					<th>เงินทุนการ<br>ศึกษาบุตร</th>
					<th>ค่ารักษาพยาบาล</th>
					<th>ค่าเสื่อมสภาพรถ</th>
					<th>ค่าที่พัก/เดินทาง<br>ตจว</th>
					<th>ค่าที่พักอาศัย</th>
					<th>เงินช่วยเหลือ</th>
					<th>รายได้อื่นๆ</th>
					<th>#endincome</th>
					<th>#startot</th>
					<th>OT100</th>
					<th>OT100</th>
					<th>OT150</th>
					<th>OT150</th>
					<th>OT200</th>
					<th>OT200</th>
					<th>OT300</th>
					<th>OT300</th>
					<th>{rfFormatCodeTextOt101p}</th>
					<th>{rfFormatCodeTextOt101p}</th>
					<th>{rfFormatCodeTextOt105p}</th>
					<th>{rfFormatCodeTextOt105p}</th>
					<th>{rfFormatCodeTextOt102p}</th>
					<th>{rfFormatCodeTextOt102p}</th>
					<th>{rfFormatCodeTextOt103p}</th>
					<th>{rfFormatCodeTextOt103p}</th>
					<th>{rfFormatCodeTextOt104p}</th>
					<th>{rfFormatCodeTextOt104p}</th>
					<th>#endot</th>
					<th>#startoutcome</th>
					<th>หักประกัน</th>
					<th>หักค่าชุด</th>
					<th>ค่าบัตร</th>
					<th>หักเงิน<br>ออมสหกรณ์</th>
					<th>เงินกู้บ้าน</th>
					<th>หักเงินกู้ยืม</th>
					<th>หักเงินกู้ กยศ</th>
					<th>หักค่ามือถือ</th>
					<th>หักเงิน<br>สำรองจ่ายตจว</th>
					<th>หักเงิน<br>สำรองจ่ายอื่นๆ</th>
					<th>หักค่า<br>ตรวจประวัติ</th>
					<th>หักค่า<br>ตรวจสุขภาพ</th>
					<th>หักเงิน<br>กรมบังคับคดี</th>
					<th>ค่าความเสียหาย</th>
					<th>{rfFormatTextdeVisa}</th>
					<th>{rfFormatTextdeWorkP}</th>
					<th>{rfFormatTextdeLate}</th>
					<th>{rfFormatTextdeAbsent}</th>
					<th>{rfFormatTextdeMulct}</th>
					<th>หักอื่นๆ</th>
					<th>#endoutcome</th>
					<th>รวมค่าจ้าง<br>(Salary)</th>
					<th>รวมค่ารายได้<br>สวัสดิการ<br>(Income)</th>
					<th>รวมค่าทำงาน<br>ล่วงเวลา<br>(Over Time)</th>
					<th>รวมรับ<br>(salary +<br>over time + income)</th>
					<th>รวม<br>nรายการหัก</th>
					<th>รับสุทธิ</th>
					<th>รายได้สะสม</th>
					<th>เงินกองทุนส่วน</th>
					<th>ประกันสังคมสะสม<br>พนักงานสะสม</th>
					<th>ภาษีสะสม</th>
				</tr>
			</thead>
			<tbody>
				<div parser-repeat="[data_list]">

					<tr >
						<td>{record_number}</td>
						<td>{rfBranchIdBranchCode}</td>
						<td>{rfPayIdPayMonthId}</td>
						<td>{rfPayIdPayYear}</td>
						<td>{rfPayIdPayFromdate} - {rfPayIdPayTodate}</td>
						<td>{rfPayIdPayAppdate}</td>
						<td>{rfPayIdPayInformdate}</td>
						<td>{paypr_factoy_code}</td>
						<td>{rfNameIdEnpbarcode}</td>
						<td>{paypr_section}</td>
						<td>{rf_emptype_id}</td>
						<td>{paypr_wage}</td>
						<td></td>
						<td>{paypr_absent_num}</td>
						<td>{paypr_absent_pay}</td>
						<td>{paypr_bnleave_num}</td>
						<td>{paypr_bnleave_pay}</td>
						<td>{paypr_bleave_num}</td>
						<td>{paypr_bleave_pay}</td>
						<td>{paypr_aleave_num}</td>
						<td>{paypr_aleave_pay}</td>
						<td>{paypr_sleave_num}</td>
						<td>{paypr_sleave_pay}</td>
						<td>{paypr_adleave_num}</td>
						<td>{paypr_adleave_pay}</td>
						<td>{paypr_ahleave_num}</td>
						<td>{paypr_ahleave_pay}</td>
						<td>{paypr_mleave_num}</td>
						<td>{paypr_mleave_pay}</td>
						<td>{paypr_hleave_num}</td>
						<td>{paypr_hleave_pay}</td>
						<td>{paypr_oleave_num}</td>
						<td>{paypr_oleave_pay}</td>
						<td>{paypr_works1_num}</td>
						<td>{paypr_works1_pay}</td>
						<td>{paypr_works2_num}</td>
						<td>{paypr_works2_pay}</td>
						<td>{paypr_works3_num}</td>
						<td>{paypr_works3_pay}</td>
						<td>{paypr_shutdown_num}</td>
						<td>{paypr_shutdown_pay}</td>
						<td>{paypr_work_num}</td>
						<td>{paypr_work_pay}</td>
						<td></td>
						<td></td>
						<td>{paypr_declare}</td>
						<td>{paypr_sevrance}</td>
						<td>{paypr_assurance_pay}</td>
						<td>{paypr_shift}</td>
						<td>{paypr_meal}</td>
						<td>{paypr_car}</td>
						<td>{paypr_diligent}</td>
						<td>{paypr_etc}</td>
						<td>{paypr_bonus}</td>
						<td>{paypr_cola}</td>
						<td>{paypr_telephone}</td>
						<td>{paypr_skill}</td>
						<td>{paypr_position}</td>
						<td>{paypr_gas}</td>
						<td>{paypr_incentive}</td>
						<td>{paypr_profession}</td>
						<td>{paypr_license}</td>
						<td>{paypr_childship}</td>
						<td>{paypr_medical}</td>
						<td>{paypr_carde}</td>
						<td>{paypr_uptravel}</td>
						<td>{paypr_stay}</td>
						<td>{paypr_subsidy}</td>
						<td>{sumPayOther}</td>
						<td></td>
						<td></td>
						<td>{paypr_ot100_num}</td>
						<td>{paypr_ot100_pay}</td>
						<td>{paypr_ot150_num}</td>
						<td>{paypr_ot150_pay}</td>
						<td>{paypr_ot200_num}</td>
						<td>{paypr_ot200_pay}</td>
						<td>{paypr_ot300_num}</td>
						<td>{paypr_ot300_pay}</td>
						<td>{paypr_ot101_num}</td>
						<td>{paypr_ot101_pay}</td>
						<td>{paypr_ot105_num}</td>
						<td>{paypr_ot105_pay}</td>
						<td>{paypr_ot102_num}</td>
						<td>{paypr_ot102_pay}</td>
						<td>{paypr_ot103_num}</td>
						<td>{paypr_ot103_pay}</td>
						<td>{paypr_ot104_num}</td>
						<td>{paypr_ot104_pay}</td>
						<td></td>
						<td></td>
						<td>{paypr_de_assurance}</td>
						<td>{paypr_de_uniform}</td>
						<td>{paypr_de_card}</td>
						<td>{paypr_de_cooperative}</td>
						<td>{paypr_de_lond}</td>
						<td>{paypr_de_borrow}</td>
						<td>{paypr_de_elond}</td>
						<td>{paypr_de_mobile}</td>
						<td>{paypr_de_backtravel}</td>
						<td>{paypr_de_backother}</td>
						<td>{paypr_de_selfemp}</td>
						<td>{paypr_de_health}</td>
						<td>{paypr_de_debtcase}</td>
						<td>{paypr_de_pernicious}</td>
						<td>{paypr_de_visa}</td>
						<td>{paypr_de_work_p}</td>
						<td>{paypr_de_absent}</td>
						<td>{paypr_de_late}</td>
						<td>{paypr_de_mulct}</td>
						<td>{sumPaydeOther}</td>
						<td></td>
						<td>{paypr_wsum_pay}</td>
						<td>{paypr_income_sum}</td>
						<td>{rfPayaheadIdAheadPay}</td>
						<td>{sumPaysalary}</td>
						<td>{paypr_de_total}</td>
						<td>{paypr_salary_net}</td>
						<td>{paypr_totalsalary}</td>
						<td>{paypr_totalfun}</td>
						<td>{paypr_totalsso}</td>
						<td>{paypr_totaltax}</td>
					</tr>
				</div>
				</tbody>

			</table>
			
