
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />

			<table border="1">
				<thead class="well">
				<tr>
					<th>NumberP</th>
					<th>Customer_id</th>
					<th>เดือน</th>
					<th>ปี</th>
					<th>Preiodpay</th>
					<th>วันที่จ่ายเงิน</th>
					<th>Name_id</th>
					<th>Employee code</th>
					<th>คำนำหน้าชื่อ</th>
					<th>ชื่อ</th>
					<th>สกุล</th>
					<th>วันที่เริ่มงาน</th>
					<th>วันที่ลาออก</th>
					<th>ตำแหน่ง</th>
					<th>แผนก</th>
					<th>ประเภท</th>
					<th>ค่าจ้าง</th>
					<th>ลากิจ_วัน</th>
					<th>ลากิจ_บาท</th>
					<th>ประเพณี_วัน</th>
					<th>ประเพณี_บาท</th>
					<th>พักร้อน_วัน</th>
					<th>พักร้อน_บาท</th>
					<th>ป่วย_วัน</th>
					<th>ป่วย_บาท</th>
					<th>อบ100_วัน</th>
					<th>อบ100_บาท</th>
					<th>อบ40_วัน</th>
					<th>อบ40_บาท</th>
					<th>คลอด_วัน</th>
					<th>คลอด_บาท</th>
					<th>ลาอื่น_วัน</th>
					<th>ลาอื่น_บาท</th>
					<th>วันทำงานพิเศษ1_วัน</th>
					<th>วันทำงานพิเศษ1_บาท</th>
					<th>วันทำงานพิเศษ2_วัน</th>
					<th>วันทำงานพิเศษ2_บาท</th>
					<th>วันทำงานพิเศษ3_วัน</th>
					<th>วันทำงานพิเศษ3_บาท</th>
					<th>shut down_วัน</th>
					<th>shut down_บาท</th>
					<th>วันทำงาน_วัน</th>
					<th>วันทำงาน_บาท</th>
					<th>รวมค่าจ้าง</th>
					<th>ค่ากะ</th>
					<th>ค่าอาหาร</th>
					<th>ค่ารถ</th>
					<th>เบี้ยขยัน</th>
					<th>โบนัส</th>
					<th>ค่าครองชีพ</th>
					<th>ค่าโทร</th>
					<th>ค่าทักษะ</th>
					<th>ค่าเบี้ยเลี้ยง</th>
					<th>Income1p</th>
					<th>Income2p</th>
					<th>Income3p</th>
					<th>Income4p</th>
					<th>Income5p</th>
					<th>Income6p</th>
					<th>Income7p</th>
					<th>Income8p</th>
					<th>Income9p</th>
					<th>Income10p</th>
					<th>Income11p</th>
					<th>Income12p</th>
					<th>คืนเงินประกัน</th>
					<th>ค่าอื่นๆ</th>
					<th>ค่าชดเชย</th>
					<th>ค่าบอกกล่าว</th>
					<th>รวมค่ารายได้สวัสดิการ</th>
					<th>OT1_ชม</th>
					<th>OT1_บาท</th>
					<th>OT1.5_ชม</th>
					<th>OT1.5_บาท</th>
					<th>OT2_ชม</th>
					<th>OT2_บาท</th>
					<th>OT3_ชม</th>
					<th>OT3_บาท</th>
					<th>OT1พิเศษ_ชม</th>
					<th>OT1พิเศษ_บาท</th>
					<th>OT1.5พิเศษ_ชม</th>
					<th>OT1.5พิเศษ_บาท</th>
					<th>OT2พิเศษ_ชม</th>
					<th>OT2พิเศษ_บาท</th>
					<th>OT3พิเศษ_ชม</th>
					<th>OT3พิเศษ_บาท</th>
					<th>รวมค่าทำงานล่วงเวลา</th>
					<th>รวมรับ</th>
					<th>ค่าประกัน</th>
					<th>เงินกู้</th>
					<th>หักค่าชุด</th>
					<th>ค่าบัตร</th>
					<th>ตรวจประวัติ</th>
					<th>ตรวจสุขภาพ</th>
					<th>หักเงินกรมบังคับคดี</th>
					<th>ค่าความเสียหาย</th>
					<th>OutCome1p</th>
					<th>OutCome2p</th>
					<th>OutCome3p</th>
					<th>OutCome4p</th>
					<th>OutCome5p</th>
					<th>ATM</th>
					<th>ประกันสังคม</th>
					<th>ภาษี</th>
					<th>เงินกองทุน</th>
					<th>หักอื่นๆ</th>
					<th>รวมรายการหัก</th>
					<th>รับสุทธิ</th>
					<th>รายได้สะสม</th>
					<th>กองทุนสะสมพนักงาน</th>
					<th>ประกันสังคมสะสม</th>
					<th>ภาษีสะสม</th>
				</tr>
			</thead>
			<tbody>
				<div parser-repeat="[data_list]">

					<tr >
						<td>{record_number}</td>
						<td>{rfBranchIdBranchCode}</td>
						<td>{rfPayIdPayMonthId}</td>
						<td>{rfPayIdPayYear}</td>
						<td>{rfPayIdPayFromdate} - {rfPayIdPayTodate}</td>
						<td>{rfPayIdPayAppdate}</td>
						<td>{rf_name_id}</td>
						<td>{paypr_factoy_code}</td>
						<td>{rfPernameIdPreName}</td>
						<td>{rfNameIdEmpName}</td>
						<td>{rfNameIdEmpSurname}</td>
						<td>{rfNameIdStartDate}</td>
						<td>{rfNameIdEndDate}</td>
						<td>{rfNameIdPositionId}</td>
						<td>{paypr_section}</td>
						<td>{rf_emptype_id}</td>
						<td>{paypr_wage}</td>
						<td>{paypr_bleave_num}</td>
						<td>{paypr_bleave_pay}</td>
						<td>{paypr_hleave_num}</td>
						<td>{paypr_hleave_pay}</td>
						<td>{paypr_aleave_num}</td>
						<td>{paypr_aleave_pay}</td>
						<td>{paypr_sleave_num}</td>
						<td>{paypr_sleave_pay}</td>
						<td>{paypr_adleave_num}</td>
						<td>{paypr_adleave_pay}</td>
						<td>{paypr_ahleave_num}</td>
						<td>{paypr_ahleave_pay}</td>
						<td>{paypr_mleave_num}</td>
						<td>{paypr_mleave_pay}</td>
						<td>{paypr_oleave_num}</td>
						<td>{paypr_oleave_pay}</td>
						<td>{paypr_works1_num}</td>
						<td>{paypr_works1_pay}</td>
						<td>{paypr_works2_num}</td>
						<td>{paypr_works2_pay}</td>
						<td>{paypr_works3_num}</td>
						<td>{paypr_works3_pay}</td>
						<td>{paypr_shutdown_num}</td>
						<td>{paypr_shutdown_pay}</td>
						<td>{paypr_work_num}</td>
						<td>{paypr_work_pay}</td>
						<td>{paypr_wsum_pay}</td>
						<td>{paypr_shift}</td>
						<td>{paypr_meal}</td>
						<td>{paypr_car}</td>
						<td>{paypr_diligent}</td>
						<td>{paypr_bonus}</td>
						<td>{paypr_cola}</td>
						<td>{paypr_telephone}</td>
						<td>{paypr_skill}</td>
						<td>{paypr_etc}</td>
						<td>{paypr_income1}</td>
						<td>{paypr_income2}</td>
						<td>{paypr_income3}</td>
						<td>{paypr_income4}</td>
						<td>{paypr_income5}</td>
						<td>{paypr_income6}</td>
						<td>{paypr_income7}</td>
						<td>{paypr_income8}</td>
						<td>{paypr_income9}</td>
						<td>{paypr_income10}</td>
						<td>{paypr_income11}</td>
						<td>{paypr_income12}</td>
						<td>{paypr_assurance_pay}</td>
						<td>{paypr_other}</td>
						<td>{paypr_sevrance}</td>
						<td>{paypr_declare}</td>
						<td>{paypr_income_sum}</td>
						<td>{paypr_ot100_num}</td>
						<td>{paypr_ot100_pay}</td>
						<td>{paypr_ot150_num}</td>
						<td>{paypr_ot150_pay}</td>
						<td>{paypr_ot200_num}</td>
						<td>{paypr_ot200_pay}</td>
						<td>{paypr_ot300_num}</td>
						<td>{paypr_ot300_pay}</td>
						<td>{paypr_ot101_num}</td>
						<td>{paypr_ot101_pay}</td>
						<td>{paypr_ot105_num}</td>
						<td>{paypr_ot105_pay}</td>
						<td>{paypr_ot102_num}</td>
						<td>{paypr_ot102_pay}</td>
						<td>{paypr_ot103_num}</td>
						<td>{paypr_ot103_pay}</td>
						<td>{paypr_otsum0_pay}</td>
						<td>{paypr_salary_net}</td>
						<td>{paypr_de_assurance}</td>
						<td>{paypr_de_borrow}</td>
						<td>{paypr_de_uniform}</td>
						<td>{paypr_de_card}</td>
						<td>{paypr_de_selfemp}</td>
						<td>{paypr_de_health}</td>
						<td>{paypr_de_debtcase}</td>
						<td>{paypr_de_pernicious}</td>
						<td>{paypr_de_out1}</td>
						<td>{paypr_de_out2}</td>
						<td>{paypr_de_out3}</td>
						<td>{paypr_de_out4}</td>
						<td>{paypr_de_out5}</td>
						<td>{paypr_de_atm}</td>
						<td>{paypr_de_ssop}</td>
						<td>{paypr_de_tax}</td>
						<td>{paypr_de_funp}</td>
						<td>{paypr_de_outother}</td>
						<td>{paypr_de_total}</td>
						<td>{paypr_salary_net}</td>
						<td>{paypr_totalsalary}</td>
						<td>{paypr_totalsso}</td>
						<td>{paypr_totalfun}</td>
						<td>{paypr_totaltax}</td>
					</tr>
				</div>
				</tbody>

			</table>
			
